bezier = open, 0.645, 0.045, 0.355, 1
bezier = close, 0.11, 0.73, 0.93, 0.02
bezier = switch, 0.5, -1, 0.265, 2
bezier = fade_move, 0.46, 0.46, 0.75, 0.77
bezier = windows_move, 1, 0, 0, 1
bezier = layers_animation, 0.87, 0.02, 0.01, 0.97
bezier = layers_fade, 0.59, 0.59, 0.59, 0.59

animation = workspaces, 1, 4, switch, slidefadevert
animation = windowsIn, 1, 3.3, open, popin
animation = windowsOut, 1, 3.3, close, popin
animation = windowsMove, 1, 3, windows_move
animation = fadeIn, 1, 2, default
animation = fadeOut, 1, 2, default
animation = fadeSwitch, 1, 2, windows_move
animation = fadeShadow, 1, 2, default
animation = fadeDim, 1, 2, default
animation = fadeLayers, 1, 1, windows_move
animation = layersIn, 1, 1, default, slide
animation = layersOut, 1, 1, windows_move, slide

# Отключение анимаций для выборщика hyprshot
layerrule {
  name            = no_anim_for_hyprshot_selection
  no_anim         = true
  match:namespace = selection
}
