exec-once = dbus-update-activation-environment --systemd --all
exec-once = pgrep -x swww-daemon || swww-daemon &
exec-once = pgrep -x swayosd-server || swayosd-server &
exec-once = pgrep -x udiskie || udiskie -n --appindicator --no-automount &
exec-once = pgrep -x lxqt-policykit-agent || lxqt-policykit-agent &
exec-once = pgrep -x waybar || waybar &
exec-once = pgrep -x dunst || dunst &
exec-once = gammastep -c ~/.config/gammastep/config.ini &
exec-once = pgrep -x hypridle || hypridle &
exec-once = wl-paste --watch cliphist store &
exec-once = nextcloud &
exec-once = clipcascade &
exec-once = keepassxc &
