monitorv2 {
    output   = eDP-1
    mode     = 2048x1280@120
    position = auto
    scale    =  1

    bitdepth = 10
    cm      = auto

    vrr     = 1
}

source = envVars.conf
source = autostart.conf
source = animations.conf
source = commonBinds.conf
source = common.conf
source = winRules.conf

input {
      sensitivity    = 0.9
      accel_profile  = adaptive
      natural_scroll = true
      kb_layout      = us, ru
      kb_variant     = dvorak,
      kb_options     = grp:win_space_toggle
}

bind = SUPER_ALT, L, exec, bemenu-lockscreen

bind = SUPER_ALT, 1, movetoworkspacesilent, 1
bind = SUPER_ALT, 2, movetoworkspacesilent, 2
bind = SUPER_ALT, 3, movetoworkspacesilent, 3
bind = SUPER_ALT, 4, movetoworkspacesilent, 4
bind = SUPER_ALT, 5, movetoworkspacesilent, 5
bind = SUPER_ALT, 6, movetoworkspacesilent, 6
bind = SUPER_ALT, 7, movetoworkspacesilent, 7
bind = SUPER_ALT, 8, movetoworkspacesilent, 8
bind = SUPER_ALT, 9, movetoworkspacesilent, 9

binde = , XF86MonBrightnessUp, exec, swayosd-client --brightness +5
binde = , XF86MonBrightnessDown, exec, swayosd-client --brightness -5

bind = SUPER_ALT, F, togglefloating, active

bind = SUPER_ALT, M, layoutmsg, swapwithmaster
bind = SUPER_ALT, H, movewindow, l
bind = SUPER_ALT, T, movewindow, d
bind = SUPER_ALT, N, movewindow, u
bind = SUPER_ALT, S, movewindow, r

gesture = 3, vertical, workspace
