monitorv2 {
    output        = DP-1
    mode          = 2560x1440@165
    position      = auto
    scale         = 1

    bitdepth      = 10
    cm            = hdr

    vrr           = 1

    sdrbrightness = 1.3
    sdrsaturation = 1.0
}

source = envVars.conf
source = autostart.conf
source = animations.conf
source = commonBinds.conf
source = common.conf
source = winRules.conf

input {
      sensitivity    = 1
      accel_profile  = adaptive
      natural_scroll = true
      kb_layout      = us, ru
      kb_options     = grp:rshift_toggle
}

bind = SUPER_CTRL, L, exec, bemenu-lockscreen

bind = SUPER_CTRL, 1, movetoworkspacesilent, 1
bind = SUPER_CTRL, 2, movetoworkspacesilent, 2
bind = SUPER_CTRL, 3, movetoworkspacesilent, 3
bind = SUPER_CTRL, 4, movetoworkspacesilent, 4
bind = SUPER_CTRL, 5, movetoworkspacesilent, 5
bind = SUPER_CTRL, 6, movetoworkspacesilent, 6
bind = SUPER_CTRL, 7, movetoworkspacesilent, 7
bind = SUPER_CTRL, 8, movetoworkspacesilent, 8
bind = SUPER_CTRL, 9, movetoworkspacesilent, 9

bind = SUPER_CTRL, F, togglefloating, active

bind = SUPER_CTRL, M, layoutmsg, swapwithmaster
bind = SUPER_CTRL, H, movewindow, l
bind = SUPER_CTRL, T, movewindow, d
bind = SUPER_CTRL, N, movewindow, u
bind = SUPER_CTRL, S, movewindow, r
