windowrule = match:title ^(Громкость)$, float on
windowrule = match:title ^(Громкость)$, move (cursor_x-(window_w*0.55)) (cursor_y(window_h*0.03))
windowrule = match:class ^(lxqt-policykit-agent)$, float on
windowrule = match:class ^(org.strawberrymusicplayer.strawberry)$, workspace 2
windowrule = match:class ^(org.kde.ark)$, float on
windowrule = match:title ^(Копирование файлов)$, float on
windowrule = match:title ^(Подтвердить замену файлов)$, float on
windowrule = match:class ^(lxqt-archiver)$, float on
windowrule = match:title ^(Настройки)$, float on
windowrule = match:title ^(Настройки — Strawberry Music Player)$, float on
windowrule = match:title ^(Эквалайзер — Strawberry Music Player)$, float on
windowrule = match:title ^(Менеджер обложек — Strawberry Music Player)$, float on
windowrule = match:title ^(Библиотека)$, float on
windowrule = match:class ^(xdg-desktop-portal-gtk), float on
